### ISSUE TITLE
Errors in the Code

### ISSUE THREAD

**Issue by Master-Hawk** [DragonRailway/Loco_BLE_Remote#2]
Tried to verify the code and always get Error Exit Status 1 on the Loco_BLE_Control.ino fileIt would be great if would finally review and fix your code. If you don't fix it, then your should post that the coding has errors and you have no intention of fixing them.

Thanks

**Comment by rambros3d** [comment]
The error is due to the changes in the new ESP3.0 core.
**You should be fine if you use the 2.0.17**
![image](https://github.com/user-attachments/assets/9d6a22f3-c37f-45d8-ba76-20ff023b5b7c)

That said, I will update the code by November. The old version will still be avaiable in 2023 branch.
Thanks for your feedback
